# -*- coding: utf-8 -*-
"""Sheet 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iy5teyuQ4ot7QnFDWCCnp3okJdpqwkzt

# Question 1: Load and Explore the Dataset

## Import libraries
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

"""## Load the dataset"""

df = pd.read_csv("Mall_customers.csv")
df.head()

"""## Print column names"""

print(df.columns)

"""## Show data types"""

df.dtypes

"""## Check missing values"""

df.isnull().sum()

"""## Summary statistics"""

df.describe()

"""# Question 2: Prepare Data

## Encode Gender

Female = 0
Male = 1
"""

encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])

df.head()

"""## Select clustering features

We do NOT use CustomerID.
"""

X = df[[
    "Gender",
    "Age",
    "Annual Income (k$)",
    "Spending Score (1-100)"
]]

X.head()

"""# Question 3: Feature Scaling

## Scale data
"""

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled

"""# Question 4: Elbow Method

## Create empty list and Run K from 1 to 10

Parameters:

n_clusters
init='k-means++' , max_iter=300 , n_init=10 , random_state=42
"""

wcss = []

for k in range(1,11):

    model = KMeans(
        n_clusters=k,
        init="k-means++",
        max_iter=300,
        n_init=10,
        random_state=42
    )

    model.fit(X_scaled)

    wcss.append(model.inertia_)

print(wcss)

"""# Question 5: Plot Elbow Curve

## Plot elbow curve
"""

plt.figure(figsize=(8,5))

plt.plot(range(1,11), wcss, marker='o')

plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.title("Elbow Method")

plt.show()

"""Usually elbow ≈ K = 5

# Question 6: Apply K-Means

## Train final model

(Using K = 5)
"""

kmeans = KMeans(
    n_clusters=5,
    init="k-means++",
    max_iter=300,
    n_init=10,
    random_state=42
)

clusters = kmeans.fit_predict(X_scaled)

print(kmeans.cluster_centers_)

"""## Add cluster column"""

df["Cluster"] = clusters
df.head()

"""# Question 7: Visualization

## Annual Income vs Spending Score

This is the most famous visualization.
"""

plt.figure(figsize=(8,5))

plt.scatter(
    df["Annual Income (k$)"],
    df["Spending Score (1-100)"],
    c=df["Cluster"]
)

plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("Customer Segmentation")

plt.show()

"""## Age vs Spending Score"""

plt.figure(figsize=(8,5))

plt.scatter(
    df["Age"],
    df["Spending Score (1-100)"],
    c=df["Cluster"]
)

plt.xlabel("Age")
plt.ylabel("Spending Score")
plt.title("Age vs Spending Score")

plt.show()

"""# Question 8: Cluster Analysis

## Number of customers in each cluster
"""

df["Cluster"].value_counts()

"""## Average income per cluster"""

df.groupby("Cluster")["Annual Income (k$)"].mean()

"""## Average age per cluster"""

df.groupby("Cluster")["Age"].mean()

"""## Full analysis"""

df.groupby("Cluster").mean()

